### ISSUE TITLE
there is no way "to shutdown"

### ISSUE THREAD

**Issue by sspilleman** [skerit/nitpin#1]
Hi,

Thanks 4 the great work... Have 1 simple question / remark / feature request :-)

How do I shutdown? There seems to not be a "disconnect()" method or so... As a result, if I want to gracefully shutdown my app because nitpin still has a minimum of 1 worker open. So I want to quit after the work is finished, it doesn't die out and there is no other way than calling 

> process.exit(0)

Which is not.... how do I say....., "nice" ;-)
Is this something you can add? Or am I missing something?

Its basically the same as with lets say a mongodb connection. If you don't call "close()", your app stays alive

Thanks!
S.

**Comment by skerit** [comment]
Oh yeah, good point.

The individual workers do have a `destroy()` method (and that gets called automatically after 30 seconds of inactivity on the socket) 

But yeah, there should be some way to force a disconnect on the main class.

**Comment by skerit** [comment]
I added a `close` method to the main nitpin class, could you test it?
